apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
type: Opaque
data:
  DB_HOST: ZGItcG9zdGdyZXNxbC1ueWMzLTI2NTE1LWRvLXVzZXItMTIxOTg5NTctMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQ==
  DB_PORT: MjUwNjA=
  DB_NAME: czYtdXNlcgo=
  DB_USER: ZG9hZG1pbgo=
  DB_PASSWORD: QVZOU19Ia21hYXRYSkwxUWZINjBIbW5aIAo=
